// This file is auto-generated by Turbocharger.
// Check it into version control to track API changes over time.
// To regenerate: "cargo clean && rm backend_api.rs && cargo check"

async fn _turbonet_self() -> _Turbonet_SelfResponse {}

struct _Turbonet_SelfResponse {
    crypto_box_public_key: [u8; 32],
    bls_public_key: [u8; 96],
    bls_proof_of_possession: [u8; 48],
    base_url: Option<String>,
    build_id: String,
}

fn check_for_updates() -> impl Stream<Item = Result<String, tracked::StringError>> {}

fn encrypted_animal_time_stream() -> impl Stream<
    Item = Result<Vec<u8>, tracked::StringError>,
> {}

async fn getblockchaininfo() -> Result<String, tracked::StringError> {}

async fn heartbeat() -> Result<String, tracked::StringError> {}

async fn jackett_search() -> Result<JackettResults, tracked::StringError> {}

async fn mail(rowid: i64) -> Result<Vec<u8>, tracked::StringError> {}

async fn mail_list() -> Result<Vec<i64>, tracked::StringError> {}

async fn notify_client_pk(client_pk: Vec<u8>) -> Result<(), tracked::StringError> {}
