// This file is auto-generated by Turbocharger.
// Check it into version control to track API changes over time.

async fn _turbonet_self() -> _Turbonet_SelfResponse {}

struct _Turbonet_SelfResponse {
    crypto_box_public_key: [u8; 32],
    bls_public_key: [u8; 96],
    bls_proof_of_possession: [u8; 48],
    base_url: Option<String>,
    build_id: String,
}

async fn animal_time() -> String {}

fn animal_time_stream() -> impl Stream<Item = String> {}

async fn check_for_updates() -> Result<String, tracked::Error> {}

async fn getblockchaininfo() -> Result<String, tracked::Error> {}

async fn heartbeat() -> Result<String, tracked::Error> {}

fn stream_example_result() -> impl Stream<Item = Result<String, tracked::Error>> {}
