[package]
authors = ["trevyn <trevyn-git@protonmail.com>"]
edition = "2021"
name = "turbo"
publish = false
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]
name = "turbocharger_generated"
path = "src/wasm.rs"

[[bin]]
name = "turbo"
path = "src/server.rs"

[dependencies]
# dependencies for both server and wasm
anyhow = "1"
turbocharger = "0.1"
turbosql = "0.4"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"

[target.'cfg(target_arch = "wasm32")'.dependencies]
# dependencies for wasm only

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# dependencies for server only
blst = "0.3"
certbot = "0.1"
gflags = "0.3"
hex = "0.4"
log = "0.4"
opener = "0.5"
pretty_env_logger = "0.4"
rand = "0.8"
rand_chacha = "0.3"
reqwest = "0.11"
rust-embed = "6"
self_update = "0.28"
tempfile = "3"
tokio = {version = "1", features = ["full"]}
turbonet = "0.1"
warp = {version = "0.3", features = ["tls"]}

[patch.crates-io]
turbocharger = {git = "https://github.com/trevyn/turbocharger", branch = "main"}
turbonet = {git = "https://github.com/trevyn/turbonet", branch = "main"}
# turbonet = {path = "../turbonet"}
# turbosql = {git = "https://github.com/trevyn/turbosql", branch = "main"}
