[package]
authors = ["trevyn <trevyn-git@protonmail.com>"]
edition = "2021"
name = "turbo"
publish = false
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]
name = "turbocharger_generated"
path = "src/wasm.rs"

[[bin]]
name = "turbo"
path = "src/server.rs"

[dependencies]
# dependencies for both server and wasm
turbocharger = "0.1"
turbosql = "0.4"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"

[target.'cfg(target_arch = "wasm32")'.dependencies]
# dependencies for wasm only

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# dependencies for server only
certbot = "0.1"
clap = {version = "=3.0.0-rc.7", features = ["derive"]}
log = "0.4"
opener = "0.5"
pretty_env_logger = "0.4"
reqwest = "0.11"
rust-embed = "6"
self_update = "0.28"
tempfile = "3"
tokio = {version = "1", features = ["full"]}
warp = {version = "0.3", features = ["tls"]}

[patch.crates-io]
turbocharger = {git = "https://github.com/trevyn/turbocharger", branch = "main"}
turbosql = {git = "https://github.com/trevyn/turbosql", branch = "main"}
