[package]
authors = ["trevyn <trevyn-git@protonmail.com>"]
edition = "2021"
name = "turbo"
publish = false
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]
name = "turbocharger_generated"
path = "src/wasm.rs"

[[bin]]
name = "turbo"
path = "src/server.rs"

[dependencies]
# dependencies for both server and wasm
anyhow = "1"
turbocharger = {version = "0.2", features = ["full"]}
turbosql = "0.4"

[target.'cfg(target_arch = "wasm32")'.dependencies]
# dependencies for wasm only
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# dependencies for server only
acme-lib = "0.8"
animal-time = "0.1"
axum = "0.4"
gflags = "0.3"
hex = "0.4"
log = "0.4"
opener = "0.5"
pretty_env_logger = "0.4"
regex = "1"
reqwest = "0.11"
rust-embed = "6"
tempfile = "3"
tokio = {version = "1", features = ["macros", "rt-multi-thread"]}
turbonet = "0.1"

[build-dependencies]
time = {version = "0.3", features = ["formatting"]}

[patch.crates-io]
rusqlite = {git = "https://github.com/rusqlite/rusqlite", branch = "master"}
# turbocharger = {path = "../turbocharger/turbocharger"}
turbocharger = {git = "https://github.com/trevyn/turbocharger", branch = "axum"}
turbonet = {git = "https://github.com/trevyn/turbonet", branch = "main"}
turbosql = {git = "https://github.com/trevyn/turbosql", branch = "main"}

[profile.dev]
incremental = false # see https://github.com/dtolnay/inventory/issues/24
