[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
ignore = [
  "RUSTSEC-2020-0071", # `time` 0.1
]
notice = "deny"
unmaintained = "deny"
unsound = "deny"
vulnerability = "deny"
yanked = "deny"

[licenses]
allow = [
  "MPL-2.0",
]
copyleft = "deny"
default = "allow"
unlicensed = "allow"

[bans]
highlight = "all"
multiple-versions = "warn"
wildcards = "warn"

[sources]
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
unknown-git = "allow"
unknown-registry = "deny"
