name: ci

on:
  push:
  pull_request:
  schedule: [cron: '40 1 * * *']

env:
  CARGO_TERM_COLOR: always

jobs:
  assign:
    name: assign build_id
    runs-on: buildjet-4vcpu-ubuntu-2004
    
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

      - run: cargo install animal-time
      - run: animal-time > build_id
      - run: cat build_id

      - uses: actions/upload-artifact@v2
        with:
          name: build_id
          path: build_id

  checklinks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: trevyn/lychee-action@v1
        id: lychee
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ./**/*.* --verbose --no-progress --exclude-all-private --base="http://127.0.0.1" --headers="accept=text/html" --scheme=http --scheme=https

      - name: Fail if there were link-check errors
        run: exit ${{ steps.lychee.outputs.exit_code }}

  test:
    name: test rust ${{ matrix.rust }} ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}

    env:
      RUSTFLAGS: '--cfg turbocharger_test'

    strategy:
      fail-fast: false
      matrix:
        os: [buildjet-4vcpu-ubuntu-2004]
        rust: [stable, beta, nightly]

    steps:
      - uses: actions/checkout@v2

      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
          components: clippy
          targets: wasm32-unknown-unknown

      - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - run: npm run build
      - run: npm run test-ci

  build:
    needs: [assign]
    name: build rust ${{ matrix.rust }} ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [buildjet-4vcpu-ubuntu-2004]
        rust: [stable]

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build_id

      - run: cat build_id

      - run: echo "BUILD_ID=$(cat build_id)" >> $GITHUB_ENV

      - uses: actions/checkout@v2

      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
          components: clippy
          targets: wasm32-unknown-unknown

      - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - run: npm run build
      - run: cargo tree
      - run: cargo tree --target=wasm32-unknown-unknown
      - run: npm list --depth=99
      - run: npx audit-ci --low

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-${{ matrix.rust }}
          path: |
            target/release/*
            !target/release/.fingerprint/*
            !target/release/build/*
            !target/release/deps/*
            !target/release/examples/*
            !target/release/incremental/*
            !target/release/*.d
            !target/release/*.rlib
            !target/release/*.dylib
            !target/release/*.so

  release:
    needs: [assign, checklinks, build, test]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/download-artifact@v2

      - run: cat build_id/build_id

      - run: echo "BUILD_ID=$(cat build_id/build_id)" >> $GITHUB_ENV

      # - run: mv macos-latest-stable/$(basename macos-latest-stable/*) $(basename macos-latest-stable/*)-mac

      - run: mv buildjet-4vcpu-ubuntu-2004-stable/$(basename buildjet-4vcpu-ubuntu-2004-stable/*) $(basename buildjet-4vcpu-ubuntu-2004-stable/*)-linux

      - id: create_release
        uses: trevyn/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.BUILD_ID }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            **/*
